/**
 * Obsidian vault access.
 *
 * READ surface (P2): Noah reads Root's curated notes via vault_search /
 * vault_read tools — vault content is never auto-imported into memory.
 *
 * WRITE surface (P3 vault-bridge): Noah writes structured artifacts (memory
 * exports, session summaries, observations) to the `_noah/` subdirectory ONLY.
 * The agent cannot write anywhere else in the vault, ever. Every write is
 * logged. Deletion is not exposed at all.
 *
 * Security posture:
 *  - Path-jailed: every resolved path must stay within the configured vault root;
 *    traversal (`../`, absolute paths) is rejected.
 *  - WRITE jail: writes additionally must stay within `_noah/` (NOAH_WRITE_PREFIX).
 *  - Excluded subtrees: directory names in config.vault.exclude (default
 *    `.obsidian`, `06-sensitive`, `_raw`) are invisible to search and read.
 *  - Hard IP block: any path containing "shannon" (case-insensitive) is refused
 *    regardless of the exclude list (CLAUDE.md Shannon boundary). Applies to
 *    writes too: a Shannon-named write target is rejected.
 *  - Size-capped reads (config.vault.maxFileBytes) and writes (NOAH_MAX_WRITE_BYTES).
 *
 * Trust: vault content is labeled at config.vault.trust (0.9) — above conversation
 * memories (0.85), below seed (1.0). See data-boundary.wrapVaultAsData.
 */

import {
  readFileSync,
  readdirSync,
  statSync,
  existsSync,
  realpathSync,
  writeFileSync,
  appendFileSync,
  mkdirSync,
  openSync,
  readSync,
  closeSync,
} from "fs";
import { resolve, relative, sep, extname, dirname } from "path";
import { classifyProvenance, type ProvenanceResult } from "./provenance";
import { config } from "./config";
import { log } from "./logger";

const TEXT_EXTENSIONS = new Set([".md", ".markdown", ".txt"]);

// Hard-excluded directory names that the env-configured exclude list can never
// remove. Guarantees the IP-sensitive subtree and Obsidian's own config stay
// invisible even if NOAH_VAULT_EXCLUDE is misconfigured or emptied.
const ALWAYS_EXCLUDE = new Set([".obsidian", "06-sensitive"]);

// Backstop against an adversarial/huge vault (or a symlink loop) exhausting the
// walk. Hitting the cap is logged, never silent.
const WALK_FILE_CAP = 20_000;

export interface VaultFile {
  /** Vault-relative path with forward slashes (stable across platforms). */
  path: string;
  bytes: number;
}

export interface VaultSearchHit {
  path: string;
  snippet: string;
  score: number;
  /** First H1 (or filename) — surfaced so the model can pick which file to read. */
  title: string;
  /** First few H2 headers as topic hints. */
  topics: string[];
}

export interface VaultStats {
  fileCount: number;
  totalBytes: number;
}

/**
 * One row in the vault index (Level 1 awareness). Lightweight: path + title +
 * a couple of H2 topic hints + size + mtime. NOT full content — the index is a
 * table of contents, not a search corpus.
 */
export interface VaultIndexEntry {
  /** Vault-relative path with forward slashes. */
  path: string;
  /** Top-level directory (the segment before the first `/`), or "" for root files. */
  dir: string;
  /** First H1 header, or the filename (sans extension) when there's no H1. */
  title: string;
  /** First up-to-3 H2 headers as topic hints (may be empty). */
  topics: string[];
  bytes: number;
  /** Last-modified epoch millis (for recency sorting). */
  mtimeMs: number;
  /** Last-modified ISO date (display). */
  mtime: string;
}

// Top-level directories omitted from the AWARENESS INDEX specifically (distinct
// from the access-level exclusions): `_noah/` is machine-generated by Noah
// itself — indexing it would just mirror Noah's own outputs back at it. The
// access exclusions (`.obsidian`, `06-sensitive`, `_raw`, shannon) still apply
// on top of this via the shared walk security checks.
const INDEX_EXCLUDE_TOPLEVEL = new Set(["_noah"]);

// Index skips trivially small notes (empty/placeholder files) — below this they
// carry no useful title/topic signal and just pad the index.
const INDEX_MIN_BYTES = 50;

// Bytes read from each file head when building the index. Enough to capture the
// H1 title and the first couple of H2s without reading whole files (keeps index
// generation to a stat + tiny read per file).
const INDEX_HEAD_BYTES = 1024;

function vaultRoot(): string {
  return resolve(config.vault.path);
}

/**
 * Canonical (symlink-resolved) vault root. Used to re-validate the jail after
 * symlink resolution. Falls back to the plain resolved path if realpath fails.
 */
function canonicalRoot(): string {
  try {
    return realpathSync(vaultRoot());
  } catch {
    return vaultRoot();
  }
}

/** Re-check a resolved real path against the canonical root + exclusions. */
function withinJail(realPath: string, root: string): boolean {
  const rel = relative(root, realPath);
  if (rel === "" || rel.startsWith("..")) return false;
  if (resolve(root, rel) !== realPath) return false;
  if (isShannon(rel)) return false;
  if (rel.split(sep).some(segmentExcluded)) return false;
  return true;
}

/** True if the vault is configured and the root directory actually exists on disk. */
export function vaultAvailable(): boolean {
  return config.vault.enabled && existsSync(vaultRoot());
}

/** Normalize a relative path to forward slashes for stable display/keys. */
function toPosix(p: string): string {
  return p.split(sep).join("/");
}

/** A path segment is excluded if it's in the hard set or the configured list. */
function segmentExcluded(name: string): boolean {
  const lower = name.toLowerCase();
  if (ALWAYS_EXCLUDE.has(lower)) return true;
  return config.vault.exclude.some((ex) => ex.toLowerCase() === lower);
}

/** Hard IP block: never expose anything Shannon-related, whatever the exclude list. */
function isShannon(relPath: string): boolean {
  return relPath.toLowerCase().includes("shannon");
}

/**
 * Resolve a caller-supplied vault-relative path to an absolute path, enforcing the
 * jail + exclusions. Returns null if the path escapes the vault, is excluded, is
 * Shannon-related, or doesn't exist as a file.
 */
function safeResolve(relPath: string): string | null {
  if (!relPath || typeof relPath !== "string") return null;
  // Reject absolute paths and drive letters outright.
  if (/^(?:[a-zA-Z]:)?[\\/]/.test(relPath)) return null;

  const root = canonicalRoot();
  const abs = resolve(vaultRoot(), relPath);

  // Cheap lexical jail check before touching disk.
  const lexicalRel = relative(vaultRoot(), abs);
  if (lexicalRel === "" || lexicalRel.startsWith("..")) return null;

  if (!existsSync(abs)) return null;

  // Resolve symlinks and re-validate against the canonical root: statSync (and
  // readFileSync) FOLLOW symlinks, so without this a symlink inside the vault
  // pointing outside it would be readable. realpathSync canonicalizes the target.
  let real: string;
  try {
    real = realpathSync(abs);
  } catch {
    return null;
  }
  if (!withinJail(real, root)) return null;

  try {
    if (!statSync(real).isFile()) return null;
  } catch {
    return null;
  }
  return real;
}

/**
 * Recursively walk the vault, honoring exclusions and the Shannon hard block.
 * `root` is the CANONICAL (realpath-resolved) vault root; every entry is itself
 * realpath-resolved and re-validated against it before recursion/listing, so a
 * symlink or Windows junction inside the vault cannot escape the jail (Dirent
 * type flags can report a reparse-point target's type).
 */
function walk(dir: string, root: string, acc: VaultFile[]): void {
  if (acc.length >= WALK_FILE_CAP) return;
  let entries: ReturnType<typeof readdirSync>;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (acc.length >= WALK_FILE_CAP) {
      log("warn", "vault.walk.capped", { cap: WALK_FILE_CAP });
      return;
    }
    const name = entry.name;
    if (segmentExcluded(name)) continue;
    const abs = resolve(dir, name);
    let real: string;
    try {
      real = realpathSync(abs);
    } catch {
      continue;
    }
    if (!withinJail(real, root)) continue;
    let st: ReturnType<typeof statSync>;
    try {
      st = statSync(real);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      walk(real, root, acc);
    } else if (st.isFile() && TEXT_EXTENSIONS.has(extname(name).toLowerCase())) {
      acc.push({ path: toPosix(relative(root, real)), bytes: st.size });
    }
  }
}

/** List all accessible text files in the vault (excluded subtrees omitted). */
export function listVaultFiles(): VaultFile[] {
  if (!vaultAvailable()) return [];
  const root = canonicalRoot();
  const acc: VaultFile[] = [];
  walk(root, root, acc);
  acc.sort((a, b) => a.path.localeCompare(b.path));
  return acc;
}

export function vaultStats(): VaultStats {
  const files = listVaultFiles();
  return {
    fileCount: files.length,
    totalBytes: files.reduce((sum, f) => sum + f.bytes, 0),
  };
}

// ── VAULT INDEX (Level 1: know what you have) ────────────────────────────────
//
// A lightweight table of contents over the vault: for each note, its title
// (first H1) and a couple of topic hints (first H2s). Built by reading only the
// head of each file, so it stays cheap even on a 1000+ file vault. The index is
// READ-ONLY awareness — it never changes vault content.

/** Strip leading markdown header markers / formatting from a header line. */
function cleanHeader(line: string): string {
  return line
    .replace(/^#{1,6}\s+/, "") // header hashes
    .replace(/[*_`~]/g, "") // inline emphasis/code markers
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Extract a display title (first H1, falling back to the filename) and up to
 * `maxTopics` H2 headers from markdown text. Pure — operates on whatever slice
 * of the file it's handed (full content for search, head-only for the index).
 * Tolerates YAML frontmatter by skipping a leading `---` block.
 */
export function extractTitleAndTopics(
  content: string,
  fallbackName: string,
  maxTopics = 3,
): { title: string; topics: string[] } {
  let body = content;
  // Skip a leading YAML frontmatter block so `title:` keys etc. don't get
  // mistaken for headers.
  if (body.startsWith("---")) {
    const end = body.indexOf("\n---", 3);
    if (end !== -1) {
      const after = body.indexOf("\n", end + 1);
      if (after !== -1) body = body.slice(after + 1);
    }
  }
  let title = "";
  const topics: string[] = [];
  for (const raw of body.split(/\r?\n/)) {
    const line = raw.trimEnd();
    if (!title && /^#\s+\S/.test(line)) {
      title = cleanHeader(line);
    } else if (/^##\s+\S/.test(line) && topics.length < maxTopics) {
      const t = cleanHeader(line);
      if (t) topics.push(t);
    }
    if (title && topics.length >= maxTopics) break;
  }
  if (!title) title = fallbackName.replace(/\.(md|markdown|txt)$/i, "");
  return { title, topics };
}

/** Read up to `n` head bytes of an already-jailed real path. "" on any failure. */
function readHead(realPath: string, n: number): string {
  let fd: number | undefined;
  try {
    fd = openSync(realPath, "r");
    const buf = Buffer.alloc(n);
    const read = readSync(fd, buf, 0, n, 0);
    return buf.subarray(0, read).toString("utf-8");
  } catch {
    return "";
  } finally {
    if (fd !== undefined) {
      try {
        closeSync(fd);
      } catch {
        /* fd already gone */
      }
    }
  }
}

/**
 * Walk the vault and build the index. Reuses the same jail + exclusion +
 * Shannon-block as listVaultFiles (via the shared `walk`), then additionally
 * drops the `_noah/` machine-generated subtree and sub-50-byte placeholder
 * notes, and reads each file's head for title/topics. Returns entries sorted by
 * path; callers re-sort for recency views.
 */
export function buildVaultIndexEntries(): VaultIndexEntry[] {
  if (!vaultAvailable()) return [];
  const root = canonicalRoot();
  const files: VaultFile[] = [];
  walk(root, root, files);

  const entries: VaultIndexEntry[] = [];
  for (const f of files) {
    const top = f.path.split("/")[0];
    if (INDEX_EXCLUDE_TOPLEVEL.has(top.toLowerCase())) continue;
    if (f.bytes < INDEX_MIN_BYTES) continue;
    // Re-validate through the full jail before touching the file (defense in
    // depth against any listing/read TOCTOU), mirroring searchVault.
    const abs = safeResolve(f.path.split("/").join(sep));
    if (!abs) continue;
    let mtimeMs = 0;
    let mtimeIso = "";
    try {
      const st = statSync(abs);
      mtimeMs = st.mtimeMs;
      mtimeIso = st.mtime.toISOString();
    } catch {
      /* keep zero mtime — entry still useful for title/topics */
    }
    const head = readHead(abs, INDEX_HEAD_BYTES);
    const name = f.path.split("/").pop() ?? f.path;
    const { title, topics } = extractTitleAndTopics(head, name);
    const slash = f.path.indexOf("/");
    const dir = slash === -1 ? "" : f.path.slice(0, slash);
    entries.push({
      path: f.path,
      dir,
      title,
      topics,
      bytes: f.bytes,
      mtimeMs,
      mtime: mtimeIso ? mtimeIso.slice(0, 10) : "",
    });
  }
  entries.sort((a, b) => a.path.localeCompare(b.path));
  return entries;
}

/** Build a short snippet around the first query-term hit (or file head). */
function makeSnippet(content: string, terms: string[]): string {
  const max = config.vault.snippetChars;
  const lower = content.toLowerCase();
  let idx = -1;
  for (const t of terms) {
    const found = lower.indexOf(t);
    if (found !== -1 && (idx === -1 || found < idx)) idx = found;
  }
  const start = idx === -1 ? 0 : Math.max(0, idx - 40);
  return content
    .slice(start, start + max)
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Search the vault by filename + content. Simple term-frequency scoring (filename
 * matches weighted higher) — adequate for a small vault; Track 2 covers scaling to
 * a real index/retrieval pipeline. Returns up to config.vault.maxResults hits.
 */
export function searchVault(query: string): VaultSearchHit[] {
  if (!vaultAvailable()) return [];
  const terms = query
    .toLowerCase()
    .split(/\s+/)
    .map((t) => t.trim())
    .filter((t) => t.length >= 2);
  if (!terms.length) return [];

  const files = listVaultFiles();
  const hits: VaultSearchHit[] = [];

  for (const f of files) {
    if (f.bytes > config.vault.maxFileBytes) continue;
    // Re-validate through the full jail (realpath + exclusions) before reading,
    // as defense-in-depth against any TOCTOU between listing and read.
    const abs = safeResolve(f.path.split("/").join(sep));
    if (!abs) continue;
    let content: string;
    try {
      content = readFileSync(abs, "utf-8");
    } catch {
      continue;
    }
    const name = f.path.split("/").pop() ?? f.path;
    const { title, topics } = extractTitleAndTopics(content, name);
    const haystackName = f.path.toLowerCase();
    const haystackTitle = title.toLowerCase();
    const haystackTopics = topics.join(" \n ").toLowerCase();
    const haystackBody = content.toLowerCase();

    // Relevance ranking (Level 1 index upgrade): title match > topic/H2 match >
    // path/filename match > raw body frequency. This lets a query land on a note
    // whose subject lives in its H1/H2 even when the filename says nothing —
    // e.g. "Swish" in a daily note's header, not its name.
    let score = 0;
    for (const t of terms) {
      if (haystackTitle.includes(t)) score += 8;
      if (haystackTopics.includes(t)) score += 5;
      if (haystackName.includes(t)) score += 4;
      let from = 0;
      let count = 0;
      while (count < 50) {
        const at = haystackBody.indexOf(t, from);
        if (at === -1) break;
        count++;
        from = at + t.length;
      }
      score += count;
    }
    if (score > 0) {
      hits.push({
        path: f.path,
        snippet: makeSnippet(content, terms),
        score,
        title,
        topics,
      });
    }
  }

  hits.sort((a, b) => b.score - a.score);
  const limited = hits.slice(0, config.vault.maxResults);
  log("info", "vault.search", { q: query.slice(0, 80), hits: limited.length });
  return limited;
}

export interface VaultReadResult {
  ok: boolean;
  path?: string;
  content?: string;
  truncated?: boolean;
  error?: string;
}

// ── WRITE surface (vault-bridge) ─────────────────────────────────────
//
// All writes go to `_noah/`. The directory name starts with an underscore so
// Obsidian users see it visually segregated from their own notes. Noah cannot
// write outside this prefix, ever — every write path is validated by
// safeWritePath() below before any FS call.

/** Vault-relative prefix every write target must start with. Hardcoded — not
 *  env-controllable — because relaxing this is a security-property change. */
const NOAH_WRITE_PREFIX = "_noah/";

/** Hard cap per file write. 256KB is generous for a daily observation file
 *  with structured sections; a runaway export would be caught here, not after
 *  filling the disk. */
const NOAH_MAX_WRITE_BYTES = 256 * 1024;

/** File extensions Noah is allowed to write. Restrict to text formats so an
 *  accidental binary write can't smuggle anything past the rest of the jail. */
const NOAH_WRITE_EXTENSIONS = new Set([".md", ".json"]);

export interface VaultWriteOptions {
  /** Allow overwriting an existing file. Default false — refuse to clobber. */
  overwrite?: boolean;
  /** Create parent directories under `_noah/` if missing. Default true. */
  createDirs?: boolean;
}

export interface VaultWriteResult {
  ok: boolean;
  path?: string;
  bytes?: number;
  error?: string;
  /** Reason for denial when ok=false. Categorical so the caller can branch. */
  kind?:
    | "denied_prefix"
    | "denied_traversal"
    | "denied_shannon"
    | "denied_extension"
    | "denied_oversize"
    | "exists"
    | "vault_unavailable"
    | "io_error";
}

/**
 * Validate + resolve a write target. Returns null on rejection (the caller
 * logs `vault.write.denied`). On success: an absolute path under the vault
 * root + `_noah/` that's safe to write to.
 *
 * The validation is lexical only (no realpath) because the target file may not
 * yet exist — instead we (a) reject any segment containing `..`, (b) reject
 * absolute paths, (c) re-check the prefix on the resolved absolute, (d) cap
 * size, (e) cap extensions. The Shannon block applies regardless.
 */
function safeWritePath(
  relPath: string,
): { abs: string; rel: string; kind: VaultWriteResult["kind"] } | null {
  if (!relPath || typeof relPath !== "string") {
    return { abs: "", rel: "", kind: "denied_prefix" } as const;
  }
  // Normalize to forward slashes for the prefix check; reject backslashes
  // outright (caller is using a non-POSIX path).
  const norm = relPath.replace(/\\/g, "/");
  // Reject absolute and drive-letter paths.
  if (/^(?:[a-zA-Z]:)?\//.test(norm)) {
    return { abs: "", rel: "", kind: "denied_prefix" } as const;
  }
  // The prefix is the entire security boundary — must start with `_noah/`.
  if (!norm.startsWith(NOAH_WRITE_PREFIX)) {
    return { abs: "", rel: "", kind: "denied_prefix" } as const;
  }
  // Reject any `..` segment defensively (lexical check before resolve).
  const segments = norm.split("/");
  for (const s of segments) {
    if (s === ".." || s === "") {
      return { abs: "", rel: "", kind: "denied_traversal" } as const;
    }
  }
  // Reject Shannon-named paths (IP boundary).
  if (isShannon(norm)) {
    return { abs: "", rel: "", kind: "denied_shannon" } as const;
  }
  // Resolve and re-check the absolute still lives under vaultRoot()/_noah/.
  const root = vaultRoot();
  const abs = resolve(root, norm);
  const expectedRoot = resolve(root, "_noah") + sep;
  if (!(abs + sep).startsWith(expectedRoot)) {
    return { abs: "", rel: "", kind: "denied_traversal" } as const;
  }
  // Extension cap.
  const ext = extname(norm).toLowerCase();
  if (!NOAH_WRITE_EXTENSIONS.has(ext)) {
    return { abs: "", rel: "", kind: "denied_extension" } as const;
  }
  return { abs, rel: norm, kind: undefined };
}

/**
 * Write a file under `_noah/`. Returns a structured result — never throws.
 * Refuses to clobber unless overwrite=true. Creates parent dirs by default.
 */
export function writeNote(
  relPath: string,
  content: string,
  options: VaultWriteOptions = {},
): VaultWriteResult {
  if (!vaultAvailable()) {
    return { ok: false, kind: "vault_unavailable", error: "Vault is not available." };
  }
  const safe = safeWritePath(relPath);
  if (!safe || safe.kind) {
    const kind = safe?.kind ?? "denied_prefix";
    log("warn", "vault.write.denied", {
      path: String(relPath).slice(0, 200),
      kind,
    });
    return { ok: false, kind, error: `Write denied: ${kind}` };
  }
  const bytes = Buffer.byteLength(content, "utf-8");
  if (bytes > NOAH_MAX_WRITE_BYTES) {
    log("warn", "vault.write.denied", {
      path: safe.rel,
      kind: "denied_oversize",
      bytes,
      cap: NOAH_MAX_WRITE_BYTES,
    });
    return {
      ok: false,
      kind: "denied_oversize",
      error: `Write exceeds ${NOAH_MAX_WRITE_BYTES} bytes (got ${bytes}).`,
    };
  }
  const overwrite = options.overwrite === true;
  const createDirs = options.createDirs !== false;
  if (existsSync(safe.abs) && !overwrite) {
    log("warn", "vault.write.exists", { path: safe.rel });
    return {
      ok: false,
      kind: "exists",
      error: "File already exists and overwrite=false.",
    };
  }
  try {
    if (createDirs) {
      mkdirSync(dirname(safe.abs), { recursive: true });
    }
    writeFileSync(safe.abs, content, "utf-8");
    log("info", "vault.write.ok", { path: safe.rel, bytes });
    return { ok: true, path: safe.rel, bytes };
  } catch (err) {
    log("error", "vault.write.fail", {
      path: safe.rel,
      err: err instanceof Error ? err.message : String(err),
    });
    return {
      ok: false,
      kind: "io_error",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Append to a file under `_noah/`. Same jail + safety as writeNote, but adds
 * to the end. Creates the file (and parent dirs) if missing.
 */
export function appendToNote(relPath: string, content: string): VaultWriteResult {
  if (!vaultAvailable()) {
    return { ok: false, kind: "vault_unavailable", error: "Vault is not available." };
  }
  const safe = safeWritePath(relPath);
  if (!safe || safe.kind) {
    const kind = safe?.kind ?? "denied_prefix";
    log("warn", "vault.write.denied", {
      path: String(relPath).slice(0, 200),
      kind,
      op: "append",
    });
    return { ok: false, kind, error: `Append denied: ${kind}` };
  }
  const bytes = Buffer.byteLength(content, "utf-8");
  // For append, the cap applies to the appended chunk; total file size is
  // bounded by application logic + filesystem.
  if (bytes > NOAH_MAX_WRITE_BYTES) {
    log("warn", "vault.write.denied", {
      path: safe.rel,
      kind: "denied_oversize",
      bytes,
      cap: NOAH_MAX_WRITE_BYTES,
      op: "append",
    });
    return {
      ok: false,
      kind: "denied_oversize",
      error: `Append exceeds ${NOAH_MAX_WRITE_BYTES} bytes (got ${bytes}).`,
    };
  }
  try {
    mkdirSync(dirname(safe.abs), { recursive: true });
    appendFileSync(safe.abs, content, "utf-8");
    log("info", "vault.write.ok", { path: safe.rel, bytes, op: "append" });
    return { ok: true, path: safe.rel, bytes };
  } catch (err) {
    log("error", "vault.write.fail", {
      path: safe.rel,
      err: err instanceof Error ? err.message : String(err),
      op: "append",
    });
    return {
      ok: false,
      kind: "io_error",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/** Read one vault file. Path-jailed, excluded-aware, size-capped. Never throws. */
export function readVaultFile(relPath: string): VaultReadResult {
  if (!vaultAvailable()) {
    return { ok: false, error: "Vault is not available." };
  }
  const abs = safeResolve(relPath);
  if (!abs) {
    log("warn", "vault.read.denied", { path: String(relPath).slice(0, 120) });
    return {
      ok: false,
      error:
        "Path not found or not accessible (it may be outside the vault, excluded, or doesn't exist).",
    };
  }
  try {
    const buf = readFileSync(abs);
    const cap = config.vault.maxFileBytes;
    const truncated = buf.length > cap;
    const content = buf.subarray(0, cap).toString("utf-8");
    const rel = toPosix(relative(vaultRoot(), abs));
    log("info", "vault.read", { path: rel, bytes: buf.length, truncated });
    return { ok: true, path: rel, content, truncated };
  } catch (err) {
    return {
      ok: false,
      error: `Could not read file: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

// ── PROVENANCE (Okeanos Sprint 1, Stage 1) ───────────────────────────────────
//
// Every vault file Noah surfaces carries a provenance bit: did Root author it
// (trust 0.9) or was it ingested from outside Root's own writing (trust 0.5)?
// The classification logic is pure (provenance.ts); this is the read-only fs
// glue that hands it the file's frontmatter. It NEVER mutates a vault file.

/** Bytes read from a file head when we only need its frontmatter for provenance. */
const FRONTMATTER_READ_CAP = 4096;

/**
 * Read only the leading bytes of a vault file (jailed via safeResolve,
 * read-only, bounded to FRONTMATTER_READ_CAP) — enough to parse frontmatter.
 * Returns "" on any access failure. Opens with mode "r" and never writes.
 */
function readVaultHead(relPath: string): string {
  const abs = safeResolve(relPath.split("/").join(sep));
  if (!abs) return "";
  let fd: number | undefined;
  try {
    fd = openSync(abs, "r");
    const buf = Buffer.alloc(FRONTMATTER_READ_CAP);
    const n = readSync(fd, buf, 0, FRONTMATTER_READ_CAP, 0);
    return buf.subarray(0, n).toString("utf-8");
  } catch {
    return "";
  } finally {
    if (fd !== undefined) {
      try {
        closeSync(fd);
      } catch {
        /* fd already gone — nothing to do */
      }
    }
  }
}

/**
 * Provenance + trust for a surfaced vault file (Stage 1). READ-ONLY: derived
 * from the path + the file's frontmatter; the vault file is never modified.
 * Pass `content` when the caller already read the whole file (vault_read) to
 * avoid a second read; otherwise only the file head is read (vault_search hits).
 * Fails safe: any access/parse failure leaves classification to path alone,
 * and an undeterminable path resolves to unknown/0.5.
 */
export function vaultProvenance(relPath: string, content?: string): ProvenanceResult {
  const head = content ?? readVaultHead(relPath);
  return classifyProvenance(relPath, head);
}
